# drop database donworry;
# create database donworry;
use donworry;

INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (1, '한국은행', '001', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (2, '국민은행', '002', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (3, '기업은행', '003', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (4, '외환은행', '004', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (5, '국민은행', '007', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (6, '농협중앙회', '011', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (7, '우리은행', '020', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (8, '신한은행', '088', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (9, '하나은행', '081', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (10, 'NH농협은행', '011', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (11, '기업은행', '003', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (12, '경남은행', '039', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (13, '대구은행', '031', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (14, '부산은행', '032', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (15, '광주은행', '034', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (16, '전북은행', '037', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (17, '제주은행', '035', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (18, '울산은행', '038', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (19, '대화은행', '045', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (20, '신협중앙회', '048', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (21, '신용보증기금', '050', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (22, '수협은행', '056', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (23, '신세계은행', '057', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (24, '평화은행', '061', NOW(), NOW());
INSERT INTO bank (bank_id, name, bank_code, created_time, modified_time) VALUES (25, '대신은행', '064', NOW(), NOW());

INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (1, '신한카드', '001', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (2, 'KB국민카드', '004', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (3, '우리카드', '020', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (4, '삼성카드', '031', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (5, '현대카드', '048', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (6, '롯데카드', '056', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (7, '하나카드', '060', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (8, '국민카드', '081', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (9, '농협카드', '116', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (10, '씨티카드', '131', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (11, '신세계카드', '154', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (12, 'NH농협은행', '162', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (13, '하나은행', '163', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (14, '동양카드', '174', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (15, '외환카드', '181', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (16, '미래카드', '187', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (17, '전북은행', '188', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (18, '수협카드', '189', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (19, '새마을금고', '195', NOW(), NOW());
INSERT INTO card_company (card_company_id, card_company_name, card_company_code, created_time, modified_time) VALUES (20, '신협카드', '214', NOW(), NOW());

insert into consumption_category (consumption_category_id, consumption_category_name, created_time, modified_time) values(1, "교통", now(), now());
insert into consumption_category (consumption_category_id, consumption_category_name, created_time, modified_time) values(2, "생활", now(), now());
insert into consumption_category (consumption_category_id, consumption_category_name, created_time, modified_time) values(3, "식비", now(), now());
insert into consumption_category (consumption_category_id, consumption_category_name, created_time, modified_time) values(4, "쇼핑", now(), now());
insert into consumption_category (consumption_category_id, consumption_category_name, created_time, modified_time) values(5, "여가", now(), now());
insert into consumption_category (consumption_category_id, consumption_category_name, created_time, modified_time) values(6, "기타", now(), now());
