##db
MYSQL_USER: donworry
MYSQL_PASSWORD: donworry678
MYSQL_URL: jdbc:mysql://j9c210.p.ssafy.io/donworry?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8

##jwt
JWT_SECRET: oasijfoawiejglawkjsdfousdhofijqwekgjoasijfoaisdjfowhef

##social-google
OAUTH2_GOOGLE_ID: 959258029329-0u075vev112cmjl4ochnt3ln27j8r7hu.apps.googleusercontent.com
OAUTH2_GOOGLE_PASSWORD: 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

##email
EMAIL_ID: byuri1356@gmail.com
EMAIL_PASSWORD: enufnvmvivtowrpk

---

##dev
spring:
  config:
    activate:
      on-profile: dev

##db
MYSQL_USER: donworry
MYSQL_PASSWORD: donworry678
MYSQL_URL: jdbc:mysql://j9c210.p.ssafy.io/donworry?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8

---

##server
spring:
  config:
    activate:
      on-profile: server

##db
MYSQL_USER: donworry
MYSQL_PASSWORD: donworry678
MYSQL_URL: jdbc:mysql://j9c210.p.ssafy.io/donworry?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
